on:
  push:

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit_message
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"

      - name: Check if the commit message contains "conditions"
        id: check_message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"conditions"* ]]; then
            echo "Match found"
            echo "check_success=true" >> $GITHUB_OUTPUT
          else
            echo "Match not found"
            echo "check_success=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      condition_output: ${{ steps.check-message.outputs.check_success }}

  run-success-tests:
    runs-on: ubuntu-latest
    needs: check-commit-message
    #if: needs.check-commit-message.outputs.condition_output == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        env:
          output5: ${{ needs.check-commit-message.outputs.condition_output }}
        run: |
          echo "Running success tests"
          echo $output5

  run-failure-tests:
    runs-on: ubuntu-latest
    needs: check-commit-message
    if: needs.check-commit-message.outputs.condition_output == 'false'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running failure tests"
