on:
  push:

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit_message
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"

      - name: Check if the commit message contains "conditions"
        id: check_message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"conditions"* ]]; then
            echo "Match found"
            echo "true" >> $GITHUB_ENV
          else
            echo "Match not found"
            echo "false" >> $GITHUB_ENV
          fi
    outputs:
      condition_output: ${{ GITHUB_ENV }}

  run-success-tests:
    runs-on: ubuntu-latest
    needs: check-commit-message
    if: needs.check-commit-message.outputs.condition_output == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running success tests"

  run-failure-tests:
    runs-on: ubuntu-latest
    needs: check-commit-message
    if: needs.check-commit-message.outputs.condition_output == 'false'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running failure tests"
